"""Add new fields to Job model

Revision ID: e8bcbaa5f4d7
Revises: 
Create Date: 2024-08-31 02:59:04.679865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8bcbaa5f4d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title_encoded', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location_encoded', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ctc_min_scaled', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ctc_max_scaled', sa.Float(), nullable=True))

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('job_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('ctc_max_scaled')
        batch_op.drop_column('ctc_min_scaled')
        batch_op.drop_column('location_encoded')
        batch_op.drop_column('job_title_encoded')

    # ### end Alembic commands ###
